### ISSUE TITLE
When does the challenge end?

### ISSUE THREAD

**Issue by deepakgupta1** [Vision-CAIR/3DCoMPaT-v2#2]
Somewhere it says that it ends on 16 June, on some page it says 1 June. What is the right end date?

**Comment by HabibSlim** [comment]
Dear Deepak,

Can you clarify which pages you are referring to?

Here is the website page:

![image](https://github.com/Vision-CAIR/3DCoMPaT-v2/assets/28985377/7167e8a3-0efc-498a-8e5d-22f1b1bc65c4)

Here is the Eval.AI challenge page:

![image](https://github.com/Vision-CAIR/3DCoMPaT-v2/assets/28985377/739a756b-59a7-48cc-9eeb-373dc8b0714b)

Please point me out to the page which indicates 16th June (an incorrect date), so that I may fix it :)

Habib

**Comment by HabibSlim** [comment]
@deepakgupta1 

The challenge has been extended to June 10th since we've had similar complaints from other participants.

Respectfully,
Habib
